UserReservation/UserReservation/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserReservation.Models;

namespace test.Controllers
{
    public class LoginController : Controller
    {
        public string useraccount;
        protected override void HandleUnknownAction(string actionName)

        {

            try
            {

                this.View(actionName).ExecuteResult(this.ControllerContext);

            }
            catch (InvalidOperationException ieox)

            {

                ViewData["error"] = "Unknown Action: \"" + Server.HtmlEncode(actionName) + "\"";

                ViewData["exMessage"] = ieox.Message;

                this.View("Error").ExecuteResult(this.ControllerContext);

            }

        }
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Autherize(UserReservation.Models.User user)
        {
            using (URModel _db = new URModel())
            {
                var userdetails = _db.User.Where(x => x.Username == user.Username && x.Password == user.Password).FirstOrDefault();
                if (userdetails == null)
                {

                    return RedirectToAction("Error", "Login");
                }
                else {
                    useraccount = userdetails.Username;
                    Session["userName"] = userdetails.Username;
                    var reservationInfo = (from reser in _db.reserve
                                           where reser.Username == userdetails.Username
                                           select reser).ToList(); 
                    return RedirectToAction("Index","reserves");
                }
            }
            return View();
        }

        public ActionResult Loginout() {
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }

        public ActionResult Signup()
        {
            return View();
        }
    }
}

UserReservation/UserReservation/Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserReservation.Models;

namespace test.Controllers
{
    public class SignupController : Controller
    {
        private URModel _db = new URModel();
        protected override void HandleUnknownAction(string actionName)

        {

            try
            {

                this.View(actionName).ExecuteResult(this.ControllerContext);

            }
            catch (InvalidOperationException ieox)

            {

                ViewData["error"] = "Unknown Action: \"" + Server.HtmlEncode(actionName) + "\"";

                ViewData["exMessage"] = ieox.Message;

                this.View("Error").ExecuteResult(this.ControllerContext);

            }

        }
        // GET: Signup
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SignupSuccess([Bind(Exclude = "Id")] User u)
        {
            if (!ModelState.IsValid)
                return View();

            _db.User.Add(u);
            _db.SaveChanges();

            return View();
        }
    }
}

UserReservation/UserReservation/Views/Login/Autherize.cshtml
@model UserReservation.Models.reserve
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Autherize</title>
</head>
<body>
    <div>
        <table>
            <tr>
                <td>"Autherize"</td>
            </tr>
        </table>
    </div>
    <div>
        <h3>User:@Session["userName"].ToString()</h3>
        <a href="@Url.Action("Loginout", "Login")">LogOut</a>
    </div>
</body>
</html>

UserReservation/UserReservation/Views/Login/Index.cshtml
@model UserReservation.Models.User
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        #login-div {
            position: absolute;
            left: 37%;
            top: 30%;
            border: lpx solid #000000;
            padding: 10px 10px;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div id="login-div">
        @using (Html.BeginForm("Autherize", "Login", FormMethod.Post))
        {
            <table>
                <tr>
                    <td></td>
                    <td>
                        Login
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Username)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Username)
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(model => model.Password)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Password)
                    </td>
                </tr>

                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="name" value="Login">
                        <input type="reset" name="name" value="Clear">

                    </td>
                </tr>
            </table>
        }
        @using (Html.BeginForm("Index", "Signup", FormMethod.Post))
        {
            <table>
                <tr>
                    <td></td>
                    <td><input type="submit" name="name" value="Sign up"></td>
                </tr>
            </table>
        }
    </div>
</body>
</html>